\hypertarget{structeos_1_1InternalError}{
\section{eos::InternalError Struct Reference}
\label{structeos_1_1InternalError}\index{eos::InternalError@{eos::InternalError}}
}


{\ttfamily \#include $<$exception.hh$>$}

Inherits \hyperlink{classeos_1_1Exception}{eos::Exception}.\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hyperlink{structeos_1_1InternalError_ae4b3f79d99d58833babeb1e743853390}{InternalError} (const std::string \&message)  throw ()
\end{DoxyCompactItemize}


\subsection{Constructor \& Destructor Documentation}
\hypertarget{structeos_1_1InternalError_ae4b3f79d99d58833babeb1e743853390}{
\index{eos::InternalError@{eos::InternalError}!InternalError@{InternalError}}
\index{InternalError@{InternalError}!eos::InternalError@{eos::InternalError}}
\subsubsection[{InternalError}]{\setlength{\rightskip}{0pt plus 5cm}eos::InternalError::InternalError (const std::string \& {\em message})  throw ()}}
\label{structeos_1_1InternalError_ae4b3f79d99d58833babeb1e743853390}


The documentation for this struct was generated from the following file:\begin{DoxyCompactItemize}
\item 
/home/alexshires/EOS/eos-\/next/eos/utils/\hyperlink{exception_8hh}{exception.hh}\end{DoxyCompactItemize}
